services:
  - type: web
    name: pet-grooming-saas
    env: node
    region: singapore
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma db push && npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
      - key: AUTH_TRUST_HOST
        value: true
      - key: NODE_ENV
        value: production
