-- Remove deprecated free-text fields
ALTER TABLE "Pet" DROP COLUMN IF EXISTS "diseases";
ALTER TABLE "Pet" DROP COLUMN IF EXISTS "allergies";

-- 個性標籤 (array)
ALTER TABLE "Pet" ADD COLUMN "personality" TEXT[] NOT NULL DEFAULT '{}';

-- 身體狀況
ALTER TABLE "Pet" ADD COLUMN "boneIssue" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Pet" ADD COLUMN "boneNote" TEXT;
ALTER TABLE "Pet" ADD COLUMN "skinIssue" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Pet" ADD COLUMN "skinNote" TEXT;
ALTER TABLE "Pet" ADD COLUMN "earIssue" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Pet" ADD COLUMN "earNote" TEXT;
ALTER TABLE "Pet" ADD COLUMN "eyeIssue" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Pet" ADD COLUMN "eyeNote" TEXT;

-- 病史分類
ALTER TABLE "Pet" ADD COLUMN "heartDisease" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Pet" ADD COLUMN "boneDisease" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Pet" ADD COLUMN "skinDisease" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Pet" ADD COLUMN "epilepsy" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Pet" ADD COLUMN "diabetes" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Pet" ADD COLUMN "surgeryHistory" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Pet" ADD COLUMN "surgeryNote" TEXT;
ALTER TABLE "Pet" ADD COLUMN "otherDisease" TEXT;

-- 美容習慣
ALTER TABLE "Pet" ADD COLUMN "bathFrequency" TEXT;
ALTER TABLE "Pet" ADD COLUMN "groomFrequency" TEXT;
ALTER TABLE "Pet" ADD COLUMN "blowDryerFear" TEXT;

-- 主人同意事項
ALTER TABLE "Pet" ADD COLUMN "afterGroomHandle" TEXT;
ALTER TABLE "Pet" ADD COLUMN "consentPhoto" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Pet" ADD COLUMN "consentSnack" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Pet" ADD COLUMN "snackAllergy" TEXT;
